name: Check links

on:
  push:
    branches:
      - "**"

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 1.61.0

      - name: Install mdbook
        run: cargo install mdbook

      - name: Build book
        run: mdbook build

      - name: Check links with mdbook
        run: mdbook test --no-fail
